language: node_js
node_js: '10'

addons:
  postgresql: '10'

services:
  - postgresql
  - redis-server

env:
  - POSTGRES_URL="postgres://postgres@localhost/ripple_auth" REDIS_HOST="localhost"

before_script: yarn install

script: ./ci/run.sh

after_success: ./ci/deploy.sh
